/* ==========================================================================
   TRACK DATA — generated by scripts/build-tracks.py
   --------------------------------------------------------------------------
   Add one object per track:

   {
     title:    "Track Name",                    // required
     artist:   "Artist Name",                   // required
     cover:    "assets/covers/track-01.jpg",    // jpg / png / webp
     audio:    "assets/audio/track-01.mp3",     // mp3 / wav / flac
     download: "assets/audio/track-01.mp3",     // optional ("" hides the button)
     duration: "03:42",                         // optional: read from file if empty
     category: "single",                        // "single" | "album"
     meta:     "Single · 2026",                 // optional small label
     note:     "One line about the track."      // optional, full player only
   }

   Re-run `python3 scripts/build-tracks.py` after changing the assets folder.
   ========================================================================== */

window.TRACKS = [
  {
    title: "Slow Light",
    artist: "Aria Mehr",
    cover: "assets/covers/slow-light.jpg",
    audio: "assets/audio/slow-light.mp3",
    download: "assets/audio/slow-light.mp3",
    duration: "00:36",
    category: "single",
    meta: "Single · 2026",
    note: "Warm keys recorded late at night, no overdubs."
  },
  {
    title: "Concrete Bloom",
    artist: "Aria Mehr",
    cover: "assets/covers/concrete-bloom.jpg",
    audio: "assets/audio/concrete-bloom.mp3",
    download: "assets/audio/concrete-bloom.mp3",
    duration: "00:34",
    category: "album",
    meta: "Concrete Bloom LP",
    note: "Track one from the Concrete Bloom LP."
  },
  {
    title: "Tehran, 4AM",
    artist: "Aria Mehr",
    cover: "assets/covers/tehran-4am.jpg",
    audio: "assets/audio/tehran-4am.mp3",
    download: "assets/audio/tehran-4am.mp3",
    duration: "00:40",
    category: "single",
    meta: "Single · 2025",
    note: "A loop built from a single field recording."
  },
  {
    title: "Paper Walls",
    artist: "Aria Mehr",
    cover: "assets/covers/paper-walls.jpg",
    audio: "assets/audio/paper-walls.mp3",
    download: "assets/audio/paper-walls.mp3",
    duration: "00:38",
    category: "album",
    meta: "Concrete Bloom LP",
    note: ""
  },
  {
    title: "North Window",
    artist: "Aria Mehr",
    cover: "assets/covers/north-window.jpg",
    audio: "assets/audio/north-window.mp3",
    download: "assets/audio/north-window.mp3",
    duration: "00:35",
    category: "single",
    meta: "Single · 2025",
    note: ""
  },
  {
    title: "Quiet Hours",
    artist: "Aria Mehr",
    cover: "assets/covers/quiet-hours.jpg",
    audio: "assets/audio/quiet-hours.mp3",
    download: "assets/audio/quiet-hours.mp3",
    duration: "00:42",
    category: "album",
    meta: "Concrete Bloom LP",
    note: "Closing track. Recorded in one take."
  }
];
